"""Tests for line-mode KPOINTS reading (VASPKIT-style input)."""

import pytest

pytest.importorskip("pymatgen")

from alterseek_path import KPointsModifier

LINE_MODE_RECIPROCAL = """K-Path Generated by VASPKIT.
   30
Line-Mode
Reciprocal
   0.0000000000   0.0000000000   0.0000000000     Γ
   0.5000000000   0.0000000000   0.0000000000     M

   0.5000000000   0.0000000000   0.0000000000     M
   0.2777777778   0.1111111111   0.2500000000     k

  -0.1111111111   0.3888888889   0.2500000000     k'
   0.0000000000   0.5000000000   0.0000000000     M'
"""

LINE_MODE_CARTESIAN = LINE_MODE_RECIPROCAL.replace("Reciprocal", "Cartesian")

GAMMA_MESH = """Automatic mesh
0
Gamma
4 4 4
"""


def test_reads_reciprocal_line_mode(tmp_path):
    path = tmp_path / "KPOINTS"
    path.write_text(LINE_MODE_RECIPROCAL, encoding="utf-8")
    modifier = KPointsModifier()
    assert modifier.read_kpoints_file(str(path))
    assert len(modifier.kpoints_data) == 6
    assert modifier.kpoints_data[0] == [0.0, 0.0, 0.0, "Γ"]
    assert modifier.kpoints_data[4] == [-0.1111111111, 0.3888888889, 0.25, "k'"]
    assert modifier.header_lines[2] == "Line-Mode"
    assert modifier.header_lines[3] == "Reciprocal"


def test_rejects_cartesian_line_mode(tmp_path):
    # Cartesian coordinates would be silently misread as fractional and the
    # header copied into the output file; the reader must refuse them.
    path = tmp_path / "KPOINTS"
    path.write_text(LINE_MODE_CARTESIAN, encoding="utf-8")
    modifier = KPointsModifier()
    assert not modifier.read_kpoints_file(str(path))
    assert modifier.kpoints_data == []


def test_rejects_mesh_kpoints(tmp_path):
    path = tmp_path / "KPOINTS"
    path.write_text(GAMMA_MESH, encoding="utf-8")
    modifier = KPointsModifier()
    assert not modifier.read_kpoints_file(str(path))


def test_missing_file_returns_false(tmp_path):
    modifier = KPointsModifier()
    assert not modifier.read_kpoints_file(str(tmp_path / "no_such_KPOINTS"))
