"""End-to-end submitted-cell regressions for magnetic structures."""

import io
from pathlib import Path
import sys

import numpy as np
from ase.io import read

from alterseek.kpoints import KPointsModifier, OUTPUT_DIR


REFERENCES = Path(__file__).parent / "references"
SUPERCELL_211 = REFERENCES / "SUPERCELL_211.vasp"
SUPERCELL_221 = REFERENCES / "SUPERCELL_221.vasp"
CHANGED_CELL_AM = REFERENCES / "case15_changed_cell_altermagnet.vasp"


def _mapping_matrix(path, key):
    lines = path.read_text(encoding="utf-8").splitlines()
    start = lines.index(f"{key}:") + 1
    return np.array([
        [float(value) for value in line.split()]
        for line in lines[start:start + 3]
    ])


def _kpoint_rows(path):
    rows = []
    for line in path.read_text(encoding="utf-8").splitlines()[4:]:
        fields = line.split()
        if len(fields) >= 4:
            try:
                coords = [float(value) for value in fields[:3]]
            except ValueError:
                continue
            rows.append((*coords, fields[3]))
    return rows


def _run(monkeypatch, tmp_path, structure, moments, *, operation=None):
    answers = [str(structure), "0 0 1", moments, ""]
    if operation is not None:
        answers.append(operation)
    answers.append("")
    monkeypatch.chdir(tmp_path)
    monkeypatch.setattr(sys, "stdin", io.StringIO("\n".join(answers) + "\n"))
    assert KPointsModifier().interactive_modify() is True
    return tmp_path / OUTPUT_DIR


def _assert_submitted_output_contract(tmp_path, output_dir, structure):
    stem = structure.stem
    submitted = np.asarray(read(structure).cell, dtype=float)
    mapping = output_dir / f"{stem}_seekpath_basis_mapping.txt"

    assert np.allclose(
        _mapping_matrix(mapping, "analysis_input_lattice"), submitted
    )
    assert np.allclose(
        _mapping_matrix(mapping, "kpoints_output_lattice"), submitted
    )
    assert (output_dir / f"{stem}_magnetic_primitive.mcif").exists()
    assert not (output_dir / f"{stem}_seekpath_marker_helper.vasp").exists()
    assert not (output_dir / f"{stem}_seekpath_standard.vasp").exists()
    assert not (tmp_path / f"{stem}_magnetic_primitive.vasp").exists()
    assert not (tmp_path / f"{stem}_magnetic_primitive_MAGMOM.txt").exists()


def test_determinant_one_211_basis_is_the_native_output_cell(
    tmp_path, monkeypatch, capsys
):
    output_dir = _run(
        monkeypatch,
        tmp_path,
        SUPERCELL_211,
        "1 -1 1 -1",
    )
    stdout = capsys.readouterr().out
    kpoints = tmp_path / "KPOINTS_alter"
    text = kpoints.read_text(encoding="utf-8")

    assert "Magnetic primitive cell:      SG Cmc2_1 (36)" in stdout
    assert "[12 atoms, oP1]" in stdout
    assert "Submitted analysis cell:      SG Cmc2_1 (36)" in stdout
    assert "SG SG" not in stdout
    assert "[12 atoms, oC1]" in stdout
    assert text.startswith("K-Path generated by AlterSeeK-Path (HPKOT oC1)")
    labels = {row[3] for row in _kpoint_rows(kpoints)}
    assert {"GAMMA", "Y", "C_0", "SIGMA_0", "Z", "A_0", "E_0", "T", "S", "R"} <= labels
    _assert_submitted_output_contract(
        tmp_path, output_dir, SUPERCELL_211
    )


def test_true_221_supercell_gets_native_hexagonal_labels_and_basis(
    tmp_path, monkeypatch, capsys
):
    output_dir = _run(
        monkeypatch,
        tmp_path,
        SUPERCELL_221,
        "4*8 4*-8 16*0",
        operation="1",
    )
    stdout = capsys.readouterr().out
    kpoints = tmp_path / "KPOINTS_alter"
    rows = _kpoint_rows(kpoints)

    assert "Submitted analysis cell:      SG P6_3mc (186)" in stdout
    assert "[24 atoms, hP2]" in stdout
    assert "GAMMA-M-K-GAMMA-A-L-H-A" in stdout
    assert kpoints.read_text(encoding="utf-8").startswith(
        "Selected spin-flip operation (Option 1) in submitted structure "
        "'SUPERCELL_221.vasp'"
    )
    assert any(
        label.rstrip("'") == "K"
        and np.allclose(coords, [1 / 3, 1 / 3, 0.0], atol=1e-8)
        for *coords, label in rows
    )
    _assert_submitted_output_contract(
        tmp_path, output_dir, SUPERCELL_221
    )


def test_same_volume_case15_never_replaces_the_calculation_cell(
    tmp_path, monkeypatch, capsys
):
    output_dir = _run(
        monkeypatch,
        tmp_path,
        CHANGED_CELL_AM,
        "0 2*1 2*-1 8*0",
        operation="",
    )
    stdout = capsys.readouterr().out
    kpoints_text = (tmp_path / "KPOINTS_alter").read_text(encoding="utf-8")

    assert "Magnetic primitive cell:" in stdout
    assert "SG Immm (71)" in stdout
    assert "Submitted analysis cell:" in stdout
    assert "Phase: AFM(Altermagnet)" in stdout
    assert "11 original segments -> 28 generated segments" in stdout
    assert "in submitted structure 'case15_changed_cell_altermagnet.vasp'" \
        in kpoints_text.splitlines()[0]
    _assert_submitted_output_contract(
        tmp_path, output_dir, CHANGED_CELL_AM
    )


def test_211_reuses_seekpath_fractions_without_preserving_cartesian_points(
    tmp_path, monkeypatch
):
    output_dir = _run(
        monkeypatch,
        tmp_path,
        SUPERCELL_211,
        "1 -1 1 -1",
    )
    mapping = output_dir / "SUPERCELL_211_seekpath_basis_mapping.txt"
    submitted = _mapping_matrix(mapping, "kpoints_output_lattice")
    primitive = _mapping_matrix(
        mapping, "seekpath_standard_primitive_lattice"
    )
    rotation = _mapping_matrix(mapping, "seekpath_rotation_matrix")
    b_submitted = 2 * np.pi * np.linalg.inv(submitted).T
    b_primitive = 2 * np.pi * np.linalg.inv(primitive).T

    # SeeK-path supplies Y=(-1/2,1/2,0) in its standardized oC1 primitive
    # basis. The workflow deliberately reuses that fractional triple in the
    # submitted basis, so it is not the same Cartesian reciprocal-space point.
    y_rows = [np.array(row[:3]) for row in _kpoint_rows(
        tmp_path / "KPOINTS_alter"
    ) if row[3] == "Y"]
    expected_fraction = np.array([-0.5, 0.5, 0.0])
    assert y_rows
    assert all(np.allclose(row, expected_fraction) for row in y_rows)
    standardized_cart = expected_fraction @ b_primitive @ rotation
    submitted_cart = expected_fraction @ b_submitted
    assert not np.allclose(submitted_cart, standardized_cart, atol=1e-8)
