# AlterSeeK ABINIT band-plot settings

structure = "POSCAR"
eig = "EIG"
kpoints_abinit = "KPOINTS_alter_abinit"
abo = "mnf2.abo"
emin = -5
emax = 5
fig_width = 12
fig_height = 5
gap_width_inches = 0.05
split_panels = 1
output = "alterband_abinit.png"
save_pdf = false
