"""Build validated submitted-cell marker inputs for SeeK-path."""

import os
import warnings

import numpy as np
import seekpath
import spglib
from findspingroup import find_spin_group_acc_primitive_from_data

from .io import (
    _dedupe_frac_positions,
    _group_poscar_sites,
    _load_magnetic_input_data,
    _min_periodic_cart_distance,
    _write_magnetic_mcif,
)


_MARKER_SEEDS = [
    np.array([0.11000000, 0.12000000, 0.15000001]),
    np.array([0.13000000, 0.17000000, 0.23000001]),
    np.array([0.07100000, 0.19300000, 0.31700001]),
    np.array([0.21100000, 0.13700000, 0.29300001]),
]

_MARKER_SEED_SETS = (
    (_MARKER_SEEDS[0], _MARKER_SEEDS[1]),
    (_MARKER_SEEDS[0], _MARKER_SEEDS[2]),
    (_MARKER_SEEDS[1], _MARKER_SEEDS[3]),
    (_MARKER_SEEDS[0], _MARKER_SEEDS[1], _MARKER_SEEDS[2]),
)


def _integer_point_operations(point_operations, tol=1e-7):
    """Return distinct point rotations compatible with the submitted lattice."""
    rotations = []
    for operation in point_operations:
        value = (
            operation.get("real_rotation")
            if isinstance(operation, dict)
            else operation
        )
        rotation = np.asarray(value, dtype=float)
        if rotation.shape != (3, 3) or not np.all(np.isfinite(rotation)):
            continue
        rounded = np.rint(rotation).astype(int)
        if not np.allclose(rotation, rounded, atol=tol):
            continue
        if not np.isclose(abs(np.linalg.det(rounded)), 1.0, atol=tol):
            continue
        if not any(np.array_equal(rounded, existing) for existing in rotations):
            rotations.append(rounded)
    if not rotations:
        raise RuntimeError(
            "No magnetic point operation is compatible with the submitted "
            "cell lattice."
        )
    return rotations


def _point_operation_keys(rotations):
    return {
        tuple(np.asarray(rotation, dtype=int).ravel())
        for rotation in rotations
    }


def _seekpath_lattice_tag(lattice, symprec):
    """Return the HPKOT tag of a primitive lattice from its metric alone."""
    metric_cell = (
        np.asarray(lattice, dtype=float).tolist(),
        [[0.11000000, 0.12000000, 0.15000001]],
        [1],
    )
    with warnings.catch_warnings():
        warnings.filterwarnings(
            "ignore", message=r".*dict interface is deprecated.*"
        )
        warnings.filterwarnings(
            "ignore",
            category=DeprecationWarning,
            module=r"seekpath\.hpkot(\..*)?",
        )
        result = seekpath.get_path(
            metric_cell,
            with_time_reversal=True,
            symprec=symprec,
        )
    return result["bravais_lattice_extended"]


def build_submitted_analysis_cell(
    lattice,
    real_type_numbers,
    point_operations,
    *,
    symprec=1e-3,
):
    """Build and validate an in-memory marker cell in the submitted lattice.

    The generic marker orbits encode only compatible point operations. They
    contain neither real atoms nor copies generated by hidden smaller-cell
    translations, so SeeK-path cannot reduce a deliberate submitted supercell
    to a different translation lattice.
    """
    lattice = np.asarray(lattice, dtype=float)
    if lattice.shape != (3, 3) or not np.all(np.isfinite(lattice)):
        raise ValueError("Submitted lattice must be a finite 3x3 matrix.")
    if abs(np.linalg.det(lattice)) < 1e-12:
        raise ValueError("Submitted lattice is singular.")

    real_types = {int(value) for value in real_type_numbers}
    marker_type = max(real_types, default=0) + 1
    while marker_type in real_types or marker_type <= 0:
        marker_type += 1

    rotations = _integer_point_operations(point_operations)
    intended_keys = _point_operation_keys(rotations)
    failures = []
    for seeds in _MARKER_SEED_SETS:
        markers = _dedupe_frac_positions([
            seed @ rotation.T
            for seed in seeds
            for rotation in rotations
        ])
        cell = (
            lattice.tolist(),
            [position.tolist() for position in markers],
            [marker_type] * len(markers),
        )
        dataset = spglib.get_symmetry_dataset(cell, symprec=symprec)
        seed_label = [seed.tolist() for seed in seeds]
        if dataset is None:
            failures.append(f"seeds {seed_label}: spglib found no symmetry")
            continue
        detected_keys = _point_operation_keys(dataset.rotations)
        if detected_keys != intended_keys:
            failures.append(
                f"seeds {seed_label}: intended {len(intended_keys)} point "
                f"operations but detected {len(detected_keys)}"
            )
            continue
        with warnings.catch_warnings():
            warnings.filterwarnings(
                "ignore", message=r".*dict interface is deprecated.*"
            )
            warnings.filterwarnings(
                "ignore",
                category=DeprecationWarning,
                module=r"seekpath\.hpkot(\..*)?",
            )
            sp_result = seekpath.get_path(
                cell,
                with_time_reversal=True,
                symprec=symprec,
            )
        volume_ratio = float(sp_result["volume_original_wrt_prim"])
        if not np.isclose(volume_ratio, 1.0, atol=1e-7, rtol=0.0):
            failures.append(
                f"seeds {seed_label}: volume_original_wrt_prim="
                f"{volume_ratio:.12g}"
            )
            continue
        reciprocal = 2 * np.pi * np.linalg.inv(lattice).T
        return {
            "cell": cell,
            "marker_type": marker_type,
            "marker_seeds": [seed.copy() for seed in seeds],
            "marker_count": len(markers),
            "marker_min_distance": _min_periodic_cart_distance(
                markers, lattice
            ),
            "point_operations": rotations,
            "intended_point_operation_count": len(intended_keys),
            "detected_point_operation_count": len(detected_keys),
            "volume_original_wrt_prim": volume_ratio,
            "submitted_bz_volume": abs(float(np.linalg.det(reciprocal))),
            "seekpath_bravais": sp_result["bravais_lattice_extended"],
            "point_coords": dict(sp_result["point_coords"]),
            "analysis_spacegroup_number": int(dataset.number),
            "analysis_spacegroup_symbol": str(dataset.international),
            "analysis_point_group": str(dataset.pointgroup),
        }

    raise RuntimeError(
        "Could not validate a submitted-cell marker helper without primitive "
        f"reduction. {'; '.join(failures)}"
    )


def prepare_submitted_cell_analysis(
    structure_file,
    *,
    moments_str="",
    spin_axis_cart=None,
    input_setting_operations=None,
    output_dir=".",
    symprec=1e-3,
    write_magnetic_diagnostic=False,
):
    """Prepare the validated in-memory analysis cell in the submitted lattice."""
    from ase.data import atomic_numbers

    lattice, positions, elements, moments, spin_setting = (
        _load_magnetic_input_data(structure_file, moments_str, spin_axis_cart)
    )
    real_types = [atomic_numbers[str(element)] for element in elements]
    if input_setting_operations is None:
        symmetry = spglib.get_symmetry(
            (lattice, positions, real_types),
            symprec=symprec,
        )
        if symmetry is None:
            raise RuntimeError(
                "Could not determine submitted-cell structural point operations."
            )
        point_operations = symmetry["rotations"]
    else:
        point_operations = input_setting_operations

    helper = build_submitted_analysis_cell(
        lattice,
        real_types,
        point_operations,
        symprec=symprec,
    )
    basename = os.path.splitext(os.path.basename(structure_file))[0]
    result = {
        "analysis_cell": helper["cell"],
        "analysis_marker_type": helper["marker_type"],
        "submitted_lattice": np.array(lattice, dtype=float),
        "submitted_sites": len(elements),
        "operation_basis_label": (
            f"submitted structure '{os.path.basename(structure_file)}'"
        ),
        "analysis_symmetry": {
            "number": helper["analysis_spacegroup_number"],
            "symbol": helper["analysis_spacegroup_symbol"],
            "point_group": helper["analysis_point_group"],
            "seekpath_bravais": helper["seekpath_bravais"],
        },
        "summary": {
            "marker_seeds": [
                seed.tolist() for seed in helper["marker_seeds"]
            ],
            "marker_count": helper["marker_count"],
            "marker_type": helper["marker_type"],
            "marker_min_distance": helper["marker_min_distance"],
            "intended_point_operations": helper[
                "intended_point_operation_count"
            ],
            "detected_point_operations": helper[
                "detected_point_operation_count"
            ],
            "volume_original_wrt_prim": helper[
                "volume_original_wrt_prim"
            ],
        },
    }

    if write_magnetic_diagnostic:
        fsg_result = find_spin_group_acc_primitive_from_data(
            structure_file,
            lattice,
            positions,
            elements,
            [1.0] * len(elements),
            moments,
            input_spin_setting=spin_setting,
        )
        magnetic_cell = fsg_result["acc_primitive_cell_detail"]
        magnetic_lattice = np.asarray(
            magnetic_cell["lattice"], dtype=float
        )
        magnetic_positions = [
            np.asarray(position, dtype=float)
            for position in magnetic_cell["positions"]
        ]
        magnetic_elements = [
            str(value) for value in magnetic_cell["elements"]
        ]
        magnetic_moments = np.asarray(
            magnetic_cell.get(
                "moments", np.zeros((len(magnetic_elements), 3))
            ),
            dtype=float,
        )
        _, _, grouped_positions, ordered_indices = _group_poscar_sites(
            magnetic_elements,
            magnetic_positions,
        )
        ordered_elements = [
            magnetic_elements[index] for index in ordered_indices
        ]
        ordered_moments = magnetic_moments[ordered_indices]
        os.makedirs(output_dir, exist_ok=True)
        mcif_path = os.path.join(
            output_dir, f"{basename}_magnetic_primitive.mcif"
        )
        _write_magnetic_mcif(
            mcif_path,
            f"{basename}_magnetic_primitive",
            magnetic_lattice,
            ordered_elements,
            grouped_positions,
            ordered_moments,
        )
        result.update({
            "mcif_path": mcif_path,
            "magnetic_primitive_lattice": magnetic_lattice,
            "magnetic_primitive_sites": len(magnetic_elements),
            "magnetic_primitive_lattice_tag": _seekpath_lattice_tag(
                magnetic_lattice, symprec
            ),
            "magnetic_summary": {
                "index": fsg_result.get("index"),
                "acc_symbol": fsg_result.get("acc_symbol"),
                "setting": fsg_result.get("acc_primitive_cell_setting"),
            },
        })
    return result
